Use secrets:get to get the database credentials if possible
tijsverkoyen/deployer-sumo pull request #28
Opened 2023-11-24 11:08 UTC by bjorvack

2023-11-24 12:22 UTC, tijsverkoyen requested changes

2024-01-02 15:40 UTC, bjorvack commented on recipe/database.php
> +
fixed 9efad3b56df9631aece5dabd627198470eb07c54

2024-01-02 15:40 UTC, bjorvack commented on recipe/database.php
> +
fixed 9efad3b56df9631aece5dabd627198470eb07c54

2024-01-03 07:58 UTC, tijsverkoyen approved these changes

2024-01-03 13:00 UTC, merged